In [5]:
import numpy as np

In [7]:
random_int_array = np.random.randint(1, 50, size = (10))
random_int_array

array([13, 20,  7, 20, 29, 18, 41, 21, 11, 39], dtype=int32)

In [ ]:
גודל המערך:

In [8]:
random_int_array.size

10

In [ ]:
סוג המערך:

In [9]:
random_int_array.dtype

dtype('int32')

In [ ]:
1. צרי מערך באורך 10 של מספרים שלמים רנדומליים בין 1 ל-50 וחשבי את הממוצע של המספרים

In [10]:
random_int_array = np.random.randint(1, 50, size = (10))
random_int_array

array([28, 20, 46, 27, 33,  6, 37,  1, 38, 13], dtype=int32)

In [11]:
random_int_array.mean


<function ndarray.mean>

In [14]:
random_int_array.mean()

np.float64(24.9)

In [ ]:
3. צרי מערך של 20 מספרים שלמים רנדומליים בין 1 ל-100. מצאי את כל המספרים שגדולים מ-50 במערך זה.

In [18]:
random_int_array2 = np.random.randint(1, 100, size = (20))
random_int_array2

array([31, 46, 73, 80, 32, 21, 84, 74, 15, 92, 27, 60,  5, 45, 77, 29, 87,
        9, 23,  7], dtype=int32)

In [20]:
random_int_array2 = np.random.randint(1, 100, size = (20))
condition = random_int_array2 > 50
filtered_arr = random_int_array2[condition]
filtered_arr

array([61, 88, 62, 69, 56, 65, 51, 71, 58], dtype=int32)